[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 200
# Note: via_ir disabled due to stack too deep errors with Chainlink VRF contracts

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.ci]
fuzz = { runs = 500 }
verbosity = 3

[profile.gas]
gas_reports = ["*"]

# For contract size optimization if needed
[profile.optimized]
via_ir = true
optimizer_runs = 1000